In [1]:
import os
os.chdir("/Users/sergey/PycharmProjects/Apt prices Moscow")

In [2]:
import pandas as pd

df = pd.read_csv('data/realty_data.csv')
df.head()

,product_name,period,price,postcode,address_name,lat,lon,object_type,total_square,rooms,floor,city,settlement,district,area,description,source
0,"3-комнатная, 137 м²",NaN,63000000,127473.0,"2-й Щемиловский переулок, 5а",55.778894,37.608844,Квартира,137.0,3.0,6.0,Москва,NaN,Тверской район,NaN,Просторная квартира свободной планировки с пан...,ЦИАН
1,"Студия, 16,7 м²",NaN,3250000,108815.0,"Харлампиева, 46",55.551025,37.313054,Квартира,16.7,NaN,1.0,Москва,NaN,Филимонковское поселение,NaN,ВНИМАНИЕ! ОЧЕНЬ ПРИВЛЕКАТЕЛЬНОЕ ПРЕ...,Домклик
2,"3-комнатная, 76 м²",NaN,16004680,NaN,"ЖК Прокшино, 8 к4",55.594802,37.431264,Квартира,76.0,3.0,6.0,Москва,NaN,Сосенское поселение,NaN,"Apт.1684018. 0,01% - гибкая ипотека! Воспользу...",Яндекс.Недвижимость
3,"1-комнатная, 24 м²",NaN,7841776,NaN,"ЖК Прокшино, 6 к2",55.594332,37.428099,Квартира,24.0,1.0,10.0,Москва,NaN,Сосенское поселение,NaN,Продается однокомнатная квартира № 381 в новос...,Новострой-М
4,"3-комнатная, 126 м²",NaN,120000000,121352.0,"Давыдковская, 18",55.721097,37.464342,Квартира,126.0,3.0,16.0,Москва,NaN,Фили-Давыдково район,NaN,Шикарное предложение!\nПродаётся трёхкомнатная...,Домклик

In [3]:
df.describe()

,period,price,postcode,lat,lon,total_square,rooms,floor
count,0.0,9.882200e+04,93675.000000,98822.000000,98822.000000,98822.000000,94840.000000,98822.000000
mean,NaN,2.512122e+07,124503.585119,55.742691,37.586404,66.092176,2.197427,9.905274
std,NaN,3.607234e+07,11956.742109,0.107044,0.169843,48.816204,1.038628,8.219180
min,NaN,1.900000e+06,101000.000000,55.468426,37.136489,8.000000,1.000000,1.000000
25%,NaN,1.050000e+07,115516.000000,55.673101,37.471611,40.100000,1.000000,4.000000
50%,NaN,1.516713e+07,123154.000000,55.745474,37.569365,56.400000,2.000000,8.000000
75%,NaN,2.500000e+07,140003.000000,55.817697,37.689568,75.700000,3.000000,14.000000
max,NaN,1.155219e+09,143989.000000,56.028824,38.122467,2070.000000,15.000000,66.000000

In [4]:
len(df)

98822

In [5]:
df.isnull().sum()

product_name        0
period          98822
price               0
postcode         5147
address_name        1
lat                 0
lon                 0
object_type         0
total_square        0
rooms            3982
floor               0
city             6894
settlement      91928
district        23711
area            79324
description       249
source              0
dtype: int64

In [6]:
df.head(100)

,product_name,period,price,postcode,address_name,lat,lon,object_type,total_square,rooms,floor,city,settlement,district,area,description,source
0,"3-комнатная, 137 м²",NaN,63000000,127473.0,"2-й Щемиловский переулок, 5а",55.778894,37.608844,Квартира,137.0,3.0,6.0,Москва,NaN,Тверской район,NaN,Просторная квартира свободной планировки с пан...,ЦИАН
1,"Студия, 16,7 м²",NaN,3250000,108815.0,"Харлампиева, 46",55.551025,37.313054,Квартира,16.7,NaN,1.0,Москва,NaN,Филимонковское поселение,NaN,ВНИМАНИЕ! ОЧЕНЬ ПРИВЛЕКАТЕЛЬНОЕ ПРЕ...,Домклик
2,"3-комнатная, 76 м²",NaN,16004680,NaN,"ЖК Прокшино, 8 к4",55.594802,37.431264,Квартира,76.0,3.0,6.0,Москва,NaN,Сосенское поселение,NaN,"Apт.1684018. 0,01% - гибкая ипотека! Воспользу...",Яндекс.Недвижимость
3,"1-комнатная, 24 м²",NaN,7841776,NaN,"ЖК Прокшино, 6 к2",55.594332,37.428099,Квартира,24.0,1.0,10.0,Москва,NaN,Сосенское поселение,NaN,Продается однокомнатная квартира № 381 в новос...,Новострой-М
4,"3-комнатная, 126 м²",NaN,120000000,121352.0,"Давыдковская, 18",55.721097,37.464342,Квартира,126.0,3.0,16.0,Москва,NaN,Фили-Давыдково район,NaN,Шикарное предложение!\nПродаётся трёхкомнатная...,Домклик
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"4-комнатная, 181 м²",NaN,126986160,125057.0,"Чапаевский переулок, 3",55.799163,37.520317,Квартира,181.0,4.0,34.0,Москва,NaN,Хорошёвский район,NaN,Лот 9735.\n\nКвартира с отделкой в современном...,ЦИАН
96,"1-комнатная, 38,3 м²",NaN,7500000,141068.0,"Тарасовская улица, 25",55.945253,37.839434,Квартира,38.3,1.0,24.0,Королёв,NaN,NaN,Текстильщик м-н,Арт. 32552047 Продам просторную видовую однок...,Домклик
97,"1-комнатная, 28,2 м²",NaN,4499000,141107.0,"Богородский микрорайон, 19",55.939609,37.981829,Квартира,28.2,1.0,9.0,Щёлково,NaN,NaN,Богородский м-н,Арт. 31808504 Продается однокомнатная квартира...,Домклик
98,"3-комнатная, 159,9 м²",NaN,65718900,117246.0,"Херсонская, 43 к5",55.656703,37.559221,Квартира,159.9,3.0,23.0,Москва,NaN,Черёмушки район,NaN,Продается 3-комнатная квартира в доме премиум-...,ЦИАН
99,"4-комнатная, 107 м²",NaN,59725032,115432.0,"проспект Лихачёва, 10 к2",55.690392,37.656620,Квартира,107.0,4.0,7.0,Москва,NaN,Даниловский район,NaN,Продаётся 4-комнатная квартира в ЖК «Квартал н...,Яндекс.Недвижимость

In [7]:
df = df.drop(columns=['product_name', 'period', 'lat', 'lon', 'object_type', 'area', 'description', 'source'])

In [8]:
df['postcode'].isna().sum()

np.int64(5147)

In [9]:
len(df)

98822

In [10]:
df['address_name'].value_counts().sort_index()

address_name
1 Мая, 1                    1
1 Мая, 10                   1
1 Мая, 18                   1
1 Мая, 18/1                 1
1 Мая, 22                   1
                           ..
шоссе Энтузиастов, 96 к4    1
шоссе Энтузиастов, 98 к1    2
шоссе Энтузиастов, 98 к4    2
шоссе Энтузиастов, 98 к5    2
шоссе Энтузиастов, 98 к7    2
Name: count, Length: 22083, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98822 entries, 0 to 98821
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         98822 non-null  int64
 1   postcode      93675 non-null  float64
 2   address_name  98821 non-null  object
 3   total_square  98822 non-null  float64
 4   rooms         94840 non-null  float64
 5   floor         98822 non-null  float64
 6   city          91928 non-null  object
 7   settlement    6894 non-null   object
 8   district      75111 non-null  object
dtypes: float64(4), int64(1), object(4)
memory usage: 6.8+ MB

In [12]:
n = '1-я улица Ямского Поля, 28 ст3'
adress = n.split(',')
print(adress[0])
print(adress[1])

1-я улица Ямского Поля
 28 ст3

In [13]:
import re
m = re.findall(r'\d+', adress[1])
print (m)

['28', '3']

In [14]:
type(m)

list

In [15]:
df['address_name']

0           2-й Щемиловский переулок, 5а
1                        Харлампиева, 46
2                      ЖК Прокшино, 8 к4
3                      ЖК Прокшино, 6 к2
4                       Давыдковская, 18
                      ...
98817      Кронштадтский бульвар, 9 к1/3
98818         Олимпийский проспект, вл10
98819          Чертановская улица, 53 к1
98820      1-й Грайвороновский проезд, 3
98821    Волгоградский проспект, 32/3 к6
Name: address_name, Length: 98822, dtype: object

In [16]:
df = df.dropna(subset=['address_name'])

In [17]:
df['address_name'].isna().sum()

np.int64(0)

In [18]:
def get_street(address):
    parts = address.split(',')
    street = parts[0].strip()
    house_numbers = re.findall(r'\d+', parts[1]) if len(parts) >1 else []
    return street, house_numbers

In [19]:
df[['street', 'house_number']] = df['address_name'].apply(lambda x: pd.Series(get_street(x)))

In [20]:
df

,price,postcode,address_name,total_square,rooms,floor,city,settlement,district,street,house_number
0,63000000,127473.0,"2-й Щемиловский переулок, 5а",137.0,3.0,6.0,Москва,NaN,Тверской район,2-й Щемиловский переулок,[5]
1,3250000,108815.0,"Харлампиева, 46",16.7,NaN,1.0,Москва,NaN,Филимонковское поселение,Харлампиева,[46]
2,16004680,NaN,"ЖК Прокшино, 8 к4",76.0,3.0,6.0,Москва,NaN,Сосенское поселение,ЖК Прокшино,"[8, 4]"
3,7841776,NaN,"ЖК Прокшино, 6 к2",24.0,1.0,10.0,Москва,NaN,Сосенское поселение,ЖК Прокшино,"[6, 2]"
4,120000000,121352.0,"Давыдковская, 18",126.0,3.0,16.0,Москва,NaN,Фили-Давыдково район,Давыдковская,[18]
...,...,...,...,...,...,...,...,...,...,...,...
98817,12183528,125212.0,"Кронштадтский бульвар, 9 к1/3",42.0,2.0,8.0,Москва,NaN,Головинский район,Кронштадтский бульвар,"[9, 1, 3]"
98818,34925000,129090.0,"Олимпийский проспект, вл10",63.5,2.0,3.0,Москва,NaN,Мещанский район,Олимпийский проспект,[10]
98819,10000000,117534.0,"Чертановская улица, 53 к1",34.4,1.0,3.0,Москва,NaN,Чертаново Южное район,Чертановская улица,"[53, 1]"
98820,15999000,109518.0,"1-й Грайвороновский проезд, 3",56.0,3.0,11.0,Москва,NaN,Текстильщики район,1-й Грайвороновский проезд,[3]
98821,16750000,109316.0,"Волгоградский проспект, 32/3 к6",55.1,2.0,17.0,Москва,NaN,Южнопортовый район,Волгоградский проспект,"[32, 3, 6]"

In [21]:
df['house_number'].isna().sum()

np.int64(0)

In [22]:
#все-таки лучше убрать корпуса и строения, поэтому опять меняем dataset
df['house_number'] = df['house_number'].apply(lambda x: x[0] if x else None)

In [23]:
df

,price,postcode,address_name,total_square,rooms,floor,city,settlement,district,street,house_number
0,63000000,127473.0,"2-й Щемиловский переулок, 5а",137.0,3.0,6.0,Москва,NaN,Тверской район,2-й Щемиловский переулок,5
1,3250000,108815.0,"Харлампиева, 46",16.7,NaN,1.0,Москва,NaN,Филимонковское поселение,Харлампиева,46
2,16004680,NaN,"ЖК Прокшино, 8 к4",76.0,3.0,6.0,Москва,NaN,Сосенское поселение,ЖК Прокшино,8
3,7841776,NaN,"ЖК Прокшино, 6 к2",24.0,1.0,10.0,Москва,NaN,Сосенское поселение,ЖК Прокшино,6
4,120000000,121352.0,"Давыдковская, 18",126.0,3.0,16.0,Москва,NaN,Фили-Давыдково район,Давыдковская,18
...,...,...,...,...,...,...,...,...,...,...,...
98817,12183528,125212.0,"Кронштадтский бульвар, 9 к1/3",42.0,2.0,8.0,Москва,NaN,Головинский район,Кронштадтский бульвар,9
98818,34925000,129090.0,"Олимпийский проспект, вл10",63.5,2.0,3.0,Москва,NaN,Мещанский район,Олимпийский проспект,10
98819,10000000,117534.0,"Чертановская улица, 53 к1",34.4,1.0,3.0,Москва,NaN,Чертаново Южное район,Чертановская улица,53
98820,15999000,109518.0,"1-й Грайвороновский проезд, 3",56.0,3.0,11.0,Москва,NaN,Текстильщики район,1-й Грайвороновский проезд,3
98821,16750000,109316.0,"Волгоградский проспект, 32/3 к6",55.1,2.0,17.0,Москва,NaN,Южнопортовый район,Волгоградский проспект,32

In [24]:
df['strert_house'] = df['street'] + '_' + df['house_number']

In [25]:
df

,price,postcode,address_name,total_square,rooms,floor,city,settlement,district,street,house_number,strert_house
0,63000000,127473.0,"2-й Щемиловский переулок, 5а",137.0,3.0,6.0,Москва,NaN,Тверской район,2-й Щемиловский переулок,5,2-й Щемиловский переулок_5
1,3250000,108815.0,"Харлампиева, 46",16.7,NaN,1.0,Москва,NaN,Филимонковское поселение,Харлампиева,46,Харлампиева_46
2,16004680,NaN,"ЖК Прокшино, 8 к4",76.0,3.0,6.0,Москва,NaN,Сосенское поселение,ЖК Прокшино,8,ЖК Прокшино_8
3,7841776,NaN,"ЖК Прокшино, 6 к2",24.0,1.0,10.0,Москва,NaN,Сосенское поселение,ЖК Прокшино,6,ЖК Прокшино_6
4,120000000,121352.0,"Давыдковская, 18",126.0,3.0,16.0,Москва,NaN,Фили-Давыдково район,Давыдковская,18,Давыдковская_18
...,...,...,...,...,...,...,...,...,...,...,...,...
98817,12183528,125212.0,"Кронштадтский бульвар, 9 к1/3",42.0,2.0,8.0,Москва,NaN,Головинский район,Кронштадтский бульвар,9,Кронштадтский бульвар_9
98818,34925000,129090.0,"Олимпийский проспект, вл10",63.5,2.0,3.0,Москва,NaN,Мещанский район,Олимпийский проспект,10,Олимпийский проспект_10
98819,10000000,117534.0,"Чертановская улица, 53 к1",34.4,1.0,3.0,Москва,NaN,Чертаново Южное район,Чертановская улица,53,Чертановская улица_53
98820,15999000,109518.0,"1-й Грайвороновский проезд, 3",56.0,3.0,11.0,Москва,NaN,Текстильщики район,1-й Грайвороновский проезд,3,1-й Грайвороновский проезд_3
98821,16750000,109316.0,"Волгоградский проспект, 32/3 к6",55.1,2.0,17.0,Москва,NaN,Южнопортовый район,Волгоградский проспект,32,Волгоградский проспект_32

In [26]:
df = df.drop(columns=['street', 'house_number'])

In [28]:
df = df.drop('address_name', axis=1)

In [34]:
df

,price,postcode,total_square,rooms,floor,city,settlement,district,strert_house
0,63000000,127473.0,137.0,3.0,6.0,Москва,NaN,Тверской район,2-й Щемиловский переулок_5
1,3250000,108815.0,16.7,NaN,1.0,Москва,NaN,Филимонковское поселение,Харлампиева_46
2,16004680,NaN,76.0,3.0,6.0,Москва,NaN,Сосенское поселение,ЖК Прокшино_8
3,7841776,NaN,24.0,1.0,10.0,Москва,NaN,Сосенское поселение,ЖК Прокшино_6
4,120000000,121352.0,126.0,3.0,16.0,Москва,NaN,Фили-Давыдково район,Давыдковская_18
...,...,...,...,...,...,...,...,...,...
98817,12183528,125212.0,42.0,2.0,8.0,Москва,NaN,Головинский район,Кронштадтский бульвар_9
98818,34925000,129090.0,63.5,2.0,3.0,Москва,NaN,Мещанский район,Олимпийский проспект_10
98819,10000000,117534.0,34.4,1.0,3.0,Москва,NaN,Чертаново Южное район,Чертановская улица_53
98820,15999000,109518.0,56.0,3.0,11.0,Москва,NaN,Текстильщики район,1-й Грайвороновский проезд_3
98821,16750000,109316.0,55.1,2.0,17.0,Москва,NaN,Южнопортовый район,Волгоградский проспект_32

In [40]:
df = df.rename(columns={"strert_house": "street_house"})

In [41]:
df = df.drop(columns=["settlement"])

In [46]:
cat_features = ["district", "street_house", "city", 'postcode']

In [47]:
for col in cat_features:
    df[col] = df[col].fillna("unknown").astype(str)

In [49]:
num_features = ['total_square', 'rooms', 'floor']

In [50]:
for col in num_features:
    df[col] = df[col].fillna(df[col].median())

In [83]:
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split

cat_features = ["district", "street_house", "city", 'postcode']
num_features = ['total_square', 'rooms', 'floor']

X = df[cat_features + num_features]
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = CatBoostRegressor(
    iterations=5000, #6000
    depth=14, #16
    learning_rate=0.02, #0.01
    loss_function = 'RMSE',
    cat_features=cat_features,
    verbose=200
)

model.fit(X_train, y_train, eval_set=(X_test, y_test))

0:	learn: 35405204.6595717	test: 36033141.6801676	best: 36033141.6801676 (0)	total: 95.2ms	remaining: 7m 56s
200:	learn: 10804615.7056762	test: 14559435.7413591	best: 14559435.7413591 (200)	total: 12.5s	remaining: 4m 58s
400:	learn: 8390857.5026299	test: 13362364.6987248	best: 13362364.6987248 (400)	total: 24.5s	remaining: 4m 40s
600:	learn: 7587608.8187727	test: 13085012.4011592	best: 13085012.4011592 (600)	total: 35.3s	remaining: 4m 18s
800:	learn: 6879141.2948713	test: 12862403.8591798	best: 12862403.8591798 (800)	total: 47.5s	remaining: 4m 9s
1000:	learn: 6236002.3066053	test: 12753070.8877649	best: 12753070.8877649 (1000)	total: 1m	remaining: 4m 1s
1200:	learn: 5796776.6531894	test: 12678754.9696033	best: 12678754.9696033 (1200)	total: 1m 14s	remaining: 3m 54s
1400:	learn: 5342972.3338315	test: 12620306.3137034	best: 12619659.6919495 (1393)	total: 1m 28s	remaining: 3m 48s
1600:	learn: 4961707.4718013	test: 12526798.5060523	best: 12526798.5060523 (1600)	total: 1m 43s	remaining: 3m 39s
1800:	learn: 4627881.5940472	test: 12498560.4778250	best: 12498000.4654235 (1798)	total: 1m 57s	remaining: 3m 28s
2000:	learn: 4375970.2166473	test: 12474504.7001799	best: 12474470.1407566 (1999)	total: 2m 10s	remaining: 3m 15s
2200:	learn: 4171228.4246977	test: 12466825.2618427	best: 12465318.1066426 (2178)	total: 2m 23s	remaining: 3m 1s
2400:	learn: 3997790.9331073	test: 12454943.2517631	best: 12454790.4760159 (2399)	total: 2m 35s	remaining: 2m 48s
2600:	learn: 3831859.5789729	test: 12445572.8219458	best: 12444000.1260452 (2581)	total: 2m 48s	remaining: 2m 34s
2800:	learn: 3657532.8546524	test: 12445885.4541062	best: 12444000.1260452 (2581)	total: 3m	remaining: 2m 21s
3000:	learn: 3529566.9314022	test: 12434904.7597245	best: 12434726.2419033 (2998)	total: 3m 13s	remaining: 2m 8s
3200:	learn: 3423761.1559074	test: 12426884.3407439	best: 12426646.8911184 (3175)	total: 3m 24s	remaining: 1m 55s
3400:	learn: 3330031.4344065	test: 12413710.4424135	best: 12413396.7783568 (3387)	total: 3m 36s	remaining: 1m 41s
3600:	learn: 3234810.6976232	test: 12404675.6627639	best: 12404376.0899607 (3598)	total: 3m 48s	remaining: 1m 28s
3800:	learn: 3157598.7206713	test: 12400908.6793348	best: 12400713.2396906 (3791)	total: 3m 59s	remaining: 1m 15s
4000:	learn: 3050048.4000056	test: 12393888.8940934	best: 12393636.8668405 (3995)	total: 4m 12s	remaining: 1m 3s
4200:	learn: 2961391.1862327	test: 12388014.4319341	best: 12388014.4319341 (4200)	total: 4m 25s	remaining: 50.5s
4400:	learn: 2884700.8715460	test: 12386959.1649054	best: 12386803.4919048 (4330)	total: 4m 37s	remaining: 37.8s
4600:	learn: 2811433.6947697	test: 12383750.7170598	best: 12383651.0068405 (4597)	total: 4m 49s	remaining: 25.1s
4800:	learn: 2738438.4032787	test: 12381874.8870921	best: 12381368.9270138 (4772)	total: 5m 1s	remaining: 12.5s
4999:	learn: 2669653.6541175	test: 12378550.1279447	best: 12377036.9946133 (4987)	total: 5m 14s	remaining: 0us

bestTest = 12377036.99
bestIteration = 4987

Shrink model to first 4988 iterations.

In [84]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

preds = model.predict(X_test)

mae = mean_absolute_error(y_test, preds)
mape = mean_absolute_percentage_error(y_test, preds)

print("MAE:", mae)
print("MAPE:", mape)
print("MAPE %:", mape * 100)

MAE: 3295888.086253763
MAPE: 0.103676239970351
MAPE %: 10.3676239970351

In [75]:
df["price"].mean()

np.float64(25121426.404499043)

In [85]:
model.save_model("models/catboost_model.cbm")

In [67]:
df

,price,postcode,total_square,rooms,floor,city,district,street_house
0,63000000,127473.0,137.0,3.0,6.0,Москва,Тверской район,2-й Щемиловский переулок_5
1,3250000,108815.0,16.7,2.0,1.0,Москва,Филимонковское поселение,Харлампиева_46
2,16004680,unknown,76.0,3.0,6.0,Москва,Сосенское поселение,ЖК Прокшино_8
3,7841776,unknown,24.0,1.0,10.0,Москва,Сосенское поселение,ЖК Прокшино_6
4,120000000,121352.0,126.0,3.0,16.0,Москва,Фили-Давыдково район,Давыдковская_18
...,...,...,...,...,...,...,...,...
98817,12183528,125212.0,42.0,2.0,8.0,Москва,Головинский район,Кронштадтский бульвар_9
98818,34925000,129090.0,63.5,2.0,3.0,Москва,Мещанский район,Олимпийский проспект_10
98819,10000000,117534.0,34.4,1.0,3.0,Москва,Чертаново Южное район,Чертановская улица_53
98820,15999000,109518.0,56.0,3.0,11.0,Москва,Текстильщики район,1-й Грайвороновский проезд_3
98821,16750000,109316.0,55.1,2.0,17.0,Москва,Южнопортовый район,Волгоградский проспект_32

In [69]:
!python --version

Python 3.12.4

In [70]:
import sys; sys.version

'3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)]'

In [79]:
df.to_csv('data/realty_data_cleaned.csv', index=False)